name: resq_civilian
description: A new Flutter project for ResQ Civilian.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  record: ^5.0.5
  audioplayers: ^5.2.1
  battery_plus: ^5.0.2
  geolocator: ^10.1.0
  sqflite: ^2.3.0
  uuid: ^4.2.1
  speech_to_text: ^6.5.1
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
